import { FormEvent, ReactNode, useMemo, useRef, useState } from 'react'
import type { Conversation, Message, QuickMessage, Settings } from './App'

const makeId = () => crypto.randomUUID?.() ?? `${Date.now()}-${Math.random()}`
type ShellProps = { title: string; subtitle?: string; onMenu: () => void; children: ReactNode }
function Shell({ title, subtitle, onMenu, children }: ShellProps) { return <section className="page soft-page"><header className="topbar"><button className="menu-button" onClick={onMenu} aria-label="打开菜单">☰</button><div className="top-title"><strong>{title}</strong>{subtitle && <span>{subtitle}</span>}</div><span /></header><div className="page-scroll migrated-content">{children}</div></section> }

export function AssistantPage({ value, save, onMenu }: { value: Settings; save: (s: Settings) => void; onMenu: () => void }) {
  const [form, setForm] = useState(value); const [done, setDone] = useState(false)
  return <Shell title="助手设置" subtitle="基础、人设与记忆" onMenu={onMenu}><form className="settings-form" onSubmit={e => { e.preventDefault(); save(form); setDone(true) }}><h2>基础设置</h2><label>助手名称<input value={form.assistantName} onChange={e => setForm({ ...form, assistantName: e.target.value })} /></label><label>温度：{form.temperature.toFixed(1)}<input type="range" min="0" max="2" step="0.1" value={form.temperature} onChange={e => setForm({ ...form, temperature: Number(e.target.value) })} /></label><h2>系统提示词</h2><label>定义助手的人设、语气和行为<textarea value={form.systemPrompt} onChange={e => setForm({ ...form, systemPrompt: e.target.value })} /></label><h2>长期记忆</h2><label>每次对话都会提供给助手<textarea value={form.memory} onChange={e => setForm({ ...form, memory: e.target.value })} placeholder="例如：我的生日、喜好、重要经历……" /></label><button type="submit">{done ? '已保存' : '保存助手'}</button></form></Shell>
}

export function HistoryPage({ conversations, open, remove, onMenu }: { conversations: Conversation[]; open: (c: Conversation) => void; remove: (id: string) => void; onMenu: () => void }) { return <Shell title="聊天记录" subtitle={`${conversations.length} 个历史会话`} onMenu={onMenu}>{!conversations.length ? <Empty icon="◷" text="还没有历史会话" /> : <div className="entry-list">{conversations.map(c => <article className="entry-card" key={c.id}><small>{new Date(c.updatedAt).toLocaleString('zh-CN')}</small><h3>{c.title}</h3><p>{c.messages.at(-1)?.content}</p><div className="entry-actions"><button onClick={() => open(c)}>继续聊天</button><button onClick={() => remove(c.id)}>删除</button></div></article>)}</div>}</Shell> }

export function FavoritesPage({ messages, toggle, onMenu }: { messages: Message[]; toggle: (id: string) => void; onMenu: () => void }) { const list = messages.filter(m => m.favorite); return <Shell title="收藏消息" onMenu={onMenu}>{!list.length ? <Empty icon="☆" text="聊天时点击消息旁的收藏按钮" /> : <div className="entry-list">{list.map(m => <article className="entry-card" key={m.id}><small>{m.role === 'assistant' ? '助手' : '我'}</small><p>{m.content}</p><div className="entry-actions"><button onClick={() => toggle(m.id)}>取消收藏</button></div></article>)}</div>}</Shell> }

export function SearchPage({ messages, conversations, onMenu }: { messages: Message[]; conversations: Conversation[]; onMenu: () => void }) { const [query, setQuery] = useState(''); const results = useMemo(() => [...messages, ...conversations.flatMap(c => c.messages)].filter(m => query.trim() && m.content.toLowerCase().includes(query.toLowerCase())), [query, messages, conversations]); return <Shell title="搜索消息" onMenu={onMenu}><input className="search-box" value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索所有聊天内容" />{query && <p className="result-count">找到 {results.length} 条结果</p>}<div className="entry-list">{results.map((m, i) => <article className="entry-card" key={`${m.id}-${i}`}><small>{m.role === 'assistant' ? '助手' : '我'}</small><p>{m.content}</p></article>)}</div></Shell> }

export function QuickMessagesPage({ items, setItems, onMenu }: { items: QuickMessage[]; setItems: (v: QuickMessage[]) => void; onMenu: () => void }) { const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const submit = (e: FormEvent) => { e.preventDefault(); if (!title.trim() || !content.trim()) return; setItems([{ id: makeId(), title: title.trim(), content: content.trim() }, ...items]); setTitle(''); setContent('') }; return <Shell title="快捷消息" subtitle="聊天输入框上方快捷发送" onMenu={onMenu}><form className="inline-editor" onSubmit={submit}><input value={title} onChange={e => setTitle(e.target.value)} placeholder="标题" /><input value={content} onChange={e => setContent(e.target.value)} placeholder="消息内容" /><button type="submit">添加</button></form><div className="entry-list">{items.map(item => <article className="entry-card" key={item.id}><h3>{item.title}</h3><p>{item.content}</p><div className="entry-actions"><button onClick={() => setItems(items.filter(x => x.id !== item.id))}>删除</button></div></article>)}</div></Shell> }

export function StatsPage({ current, conversations, onMenu }: { current: Message[]; conversations: Conversation[]; onMenu: () => void }) { const all = [...current, ...conversations.flatMap(c => c.messages)]; const chars = all.reduce((n, m) => n + m.content.length, 0); return <Shell title="聊天统计" onMenu={onMenu}><div className="stats-grid"><div><b>{conversations.length + 1}</b><span>总会话</span></div><div><b>{all.length}</b><span>总消息</span></div><div><b>{all.filter(m => m.role === 'user').length}</b><span>我的消息</span></div><div><b>{chars}</b><span>文字数量</span></div><div><b>{all.filter(m => m.favorite).length}</b><span>已收藏</span></div><div><b>{new Set(all.map(m => m.role)).size}</b><span>参与角色</span></div></div></Shell> }

export function BackupPage({ data, restore, onMenu }: { data: unknown; restore: (data: any) => void; onMenu: () => void }) { const file = useRef<HTMLInputElement>(null); const download = () => { const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `tumin-web-backup-${new Date().toISOString().slice(0,10)}.json`; link.click(); URL.revokeObjectURL(link.href) }; const importFile = async (selected?: File) => { if (!selected) return; try { restore(JSON.parse(await selected.text())); alert('导入成功') } catch { alert('备份文件无法识别') } }; return <Shell title="数据与备份" subtitle="网页端本地导入导出" onMenu={onMenu}><div className="backup-actions"><button onClick={download}>导出全部数据</button><button onClick={() => file.current?.click()}>导入备份</button><input ref={file} hidden type="file" accept="application/json" onChange={e => importFile(e.target.files?.[0])} /></div><p className="settings-note">备份包含网页端的设置、会话、情侣空间、快捷消息与助手记忆。API 密钥也会包含在文件中，请妥善保管。</p></Shell> }

function Empty({ icon, text }: { icon: string; text: string }) { return <div className="empty-list"><span>{icon}</span><h2>{text}</h2></div> }
