import { FormEvent, ReactNode, useState } from 'react'
import type { Appearance, MemoryLibrary, PromptItem, Provider, Settings } from './App'

const id = () => crypto.randomUUID?.() ?? `${Date.now()}-${Math.random()}`
function Shell({ title, subtitle, onMenu, children }: { title: string; subtitle?: string; onMenu: () => void; children: ReactNode }) { return <section className="page soft-page"><header className="topbar"><button className="menu-button" onClick={onMenu} aria-label="打开菜单">☰</button><div className="top-title"><strong>{title}</strong>{subtitle && <span>{subtitle}</span>}</div><span /></header><div className="page-scroll migrated-content">{children}</div></section> }

export function ProvidersPage({ items, setItems, activeId, activate, onMenu }: { items: Provider[]; setItems: (v: Provider[]) => void; activeId: string; activate: (p: Provider, model: string) => void; onMenu: () => void }) {
  const blank = { id: '', name: '', endpoint: 'https://api.openai.com/v1', apiKey: '', models: 'gpt-4o-mini', enabled: true }; const [form, setForm] = useState(blank); const [editing, setEditing] = useState(false)
  const save = (e: FormEvent) => { e.preventDefault(); if (!form.name.trim() || !form.endpoint.trim()) return; const next: Provider = { ...form, id: form.id || id(), models: form.models.split(',').map(x => x.trim()).filter(Boolean) }; setItems(form.id ? items.map(x => x.id === form.id ? next : x) : [next, ...items]); setForm(blank); setEditing(false) }
  return <Shell title="服务商与模型" subtitle="对应 APK 的服务商管理" onMenu={onMenu}><button className="primary-action" onClick={() => setEditing(true)}>＋ 添加服务商</button><div className="entry-list">{items.map(p => <article className={`entry-card provider-card ${activeId === p.id ? 'selected' : ''}`} key={p.id}><small>{p.enabled ? '已启用' : '已停用'} · {p.endpoint}</small><h3>{p.name}</h3><div className="model-chips">{p.models.map(model => <button key={model} onClick={() => activate(p, model)}>{activeId === p.id ? '✓ ' : ''}{model}</button>)}</div><div className="entry-actions"><button onClick={() => { setForm({ ...p, models: p.models.join(', ') }); setEditing(true) }}>编辑</button><button onClick={() => setItems(items.filter(x => x.id !== p.id))}>删除</button></div></article>)}</div>{editing && <div className="modal-backdrop" onClick={() => setEditing(false)}><form className="editor-modal" onSubmit={save} onClick={e => e.stopPropagation()}><h2>{form.id ? '编辑服务商' : '添加服务商'}</h2><label>名称<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>API 地址<input value={form.endpoint} onChange={e => setForm({ ...form, endpoint: e.target.value })} /></label><label>API 密钥<input type="password" value={form.apiKey} onChange={e => setForm({ ...form, apiKey: e.target.value })} /></label><label>模型 ID（逗号分隔）<textarea value={form.models} onChange={e => setForm({ ...form, models: e.target.value })} /></label><div><button type="button" onClick={() => setEditing(false)}>取消</button><button type="submit">保存</button></div></form></div>}</Shell>
}

function LibraryEditor<T extends PromptItem | MemoryLibrary>({ title, description, items, setItems, onMenu }: { title: string; description: string; items: T[]; setItems: (v: T[]) => void; onMenu: () => void }) { const [name, setName] = useState(''); const [content, setContent] = useState(''); const submit = (e: FormEvent) => { e.preventDefault(); if (!name.trim() || !content.trim()) return; setItems([{ id: id(), name: name.trim(), content: content.trim(), enabled: true } as T, ...items]); setName(''); setContent('') }; return <Shell title={title} subtitle={description} onMenu={onMenu}><form className="library-editor" onSubmit={submit}><input value={name} onChange={e => setName(e.target.value)} placeholder="名称" /><textarea value={content} onChange={e => setContent(e.target.value)} placeholder="内容" /><button type="submit">添加</button></form><div className="entry-list">{items.map(item => <article className="entry-card" key={item.id}><label className="toggle-line"><input type="checkbox" checked={item.enabled} onChange={() => setItems(items.map(x => x.id === item.id ? { ...x, enabled: !x.enabled } : x))} /><b>{item.name}</b></label><p>{item.content}</p><div className="entry-actions"><button onClick={() => setItems(items.filter(x => x.id !== item.id))}>删除</button></div></article>)}</div></Shell> }
export function PromptsPage(props: { items: PromptItem[]; setItems: (v: PromptItem[]) => void; onMenu: () => void }) { return <LibraryEditor title="提示词库" description="启用的提示词会注入聊天" {...props} /> }
export function MemoryLibrariesPage(props: { items: MemoryLibrary[]; setItems: (v: MemoryLibrary[]) => void; onMenu: () => void }) { return <LibraryEditor title="进阶记忆" description="按记忆库管理长期信息" {...props} /> }

export function AppearancePage({ value, save, onMenu }: { value: Appearance; save: (v: Appearance) => void; onMenu: () => void }) { const [form, setForm] = useState(value); return <Shell title="显示与主题" subtitle="主题、颜色与消息字号" onMenu={onMenu}><form className="settings-form" onSubmit={e => { e.preventDefault(); save(form) }}><h2>预设主题</h2><div className="theme-picks">{(['warm','rose','night'] as const).map(theme => <button type="button" className={form.theme === theme ? 'active' : ''} onClick={() => setForm({ ...form, theme })} key={theme}>{theme === 'warm' ? '暖棕' : theme === 'rose' ? '柔粉' : '夜间'}</button>)}</div><label>主色调<input type="color" value={form.primary} onChange={e => setForm({ ...form, primary: e.target.value })} /></label><label>用户气泡<input type="color" value={form.userBubble} onChange={e => setForm({ ...form, userBubble: e.target.value })} /></label><label>聊天背景<input type="color" value={form.background} onChange={e => setForm({ ...form, background: e.target.value })} /></label><label>消息字号：{form.fontSize}px<input type="range" min="12" max="21" value={form.fontSize} onChange={e => setForm({ ...form, fontSize: Number(e.target.value) })} /></label><button type="submit">应用主题</button></form></Shell> }

export function TranslatorPage({ settings, onMenu }: { settings: Settings; onMenu: () => void }) { const [input, setInput] = useState(''); const [output, setOutput] = useState(''); const [language, setLanguage] = useState('简体中文'); const [busy, setBusy] = useState(false); const translate = async () => { if (!input.trim() || busy) return; if (!settings.apiKey) { setOutput('请先配置服务商 API 密钥。'); return } setBusy(true); try { const response = await fetch(`${settings.endpoint.replace(/\/$/,'')}/chat/completions`, { method:'POST', headers:{'Content-Type':'application/json',Authorization:`Bearer ${settings.apiKey}`}, body:JSON.stringify({model:settings.model,temperature:0,messages:[{role:'system',content:`请把用户文本准确翻译为${language}，只输出译文。`},{role:'user',content:input}]}) }); if (!response.ok) throw new Error(`${response.status}`); const data = await response.json(); setOutput(data.choices?.[0]?.message?.content || '没有返回翻译结果') } catch(e) { setOutput(`翻译失败：${e instanceof Error ? e.message : '未知错误'}`) } finally { setBusy(false) } }; return <Shell title="翻译" subtitle={`使用 ${settings.model}`} onMenu={onMenu}><div className="translator"><div className="translator-toolbar"><select value={language} onChange={e => setLanguage(e.target.value)}><option>简体中文</option><option>English</option><option>日本語</option><option>한국어</option><option>Français</option></select><button onClick={() => navigator.clipboard.readText().then(setInput)}>粘贴文本</button></div><textarea value={input} onChange={e => setInput(e.target.value)} placeholder="输入需要翻译的文本" /><button className="translate-button" onClick={translate}>{busy ? '翻译中…' : '开始翻译'}</button><textarea value={output} readOnly placeholder="翻译结果" /><button onClick={() => navigator.clipboard.writeText(output)}>复制翻译结果</button></div></Shell> }
